
POST http://localhost:3000/api/v1/users

Content-Type: application/json

{
    "name": "Jason Newman",
    "email": "node@email.com",
    "password": "password"
}

GET http://localhost:3000/api/v1/users